# if you run this on Windows,

version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    environment:
      KAFKA_PORT: 9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# We shift the ports by one to avoid conflicts with the standalone Clickhouse
# container that might also be running
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8124:8123"
      - "9001:9000"
    ulimits:
      nofile: 262144
    volumes:
      - ./storage:/var/lib/clickhouse