# name: Linter

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

#   workflow_dispatch:

# jobs:
#   check:
#     runs-on: macos-latest
#     strategy:
#       matrix:
#         python-version: ["3.9"]

#     steps:
#       - name: Checking out repo
#         uses: actions/checkout@v2

#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install dependencies
#         run: make venvdev

#       - name: Linting
#         run: make lint
