name: Tests (pytest, with poetry)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  run-tests:
    name: tests-pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9"]
    defaults:
        run:
            shell: bash -l {0}

    steps:
      - name: Checking out repo
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: python -m pip install --upgrade pip poetry

      - name: Setup virtual environment
        run: poetry install

      - name: Run tests via pytest
        run: poetry run pytest
  